### ISSUE TITLE
dyld: Library not loaded: @rpath/libffmpegthumbnailer.4.dylib

### ISSUE THREAD

**Issue by stardiviner** [dirkvdb/ffmpegthumbnailer#200] opened 2021-06-09 23:59 UTC
I got error when running ffmpegthumbnailer command:

```
$ ffmpegthumbnailer -i video.mp4 -o output.jpg
dyld: Library not loaded: @rpath/libffmpegthumbnailer.4.dylib
  Referenced from: /opt/homebrew/bin/ffmpegthumbnailer
  Reason: image not found
[1]    74341 abort      ffmpegthumbnailer -i  -o output.jpg
```

I tried reinstall, and upgrade ffmpegthumbnailer. Still don't work.

My macOS system version: `Mac mini (M1, 2020) macOS Big Sur Version 11.3`

**Comment by uaos** [comment] 2021-12-31 10:08
Similar error on  macOS Monterey 12.0.1 (21A559) on Mac mini (2018):

```
ffmpegthumbnailer -s 0 -i input.mkv -o output.png -t 00:00:10

dyld[84307]: Library not loaded: /usr/local/opt/srt/lib/libsrt.1.dylib
  Referenced from: /usr/local/Cellar/ffmpeg/4.3.1_4/lib/libavformat.58.45.100.dylib
  Reason: tried: '/usr/local/opt/srt/lib/libsrt.1.dylib' (no such file), '/usr/local/lib/libsrt.1.dylib' (no such file), '/usr/lib/libsrt.1.dylib' (no such file), '/usr/local/Cellar/srt/1.4.4/lib/libsrt.1.dylib' (no such file), '/usr/local/lib/libsrt.1.dylib' (no such file), '/usr/lib/libsrt.1.dylib' (no such file)Library not loaded: /usr/local/opt/srt/lib/libsrt.1.dylib
  Referenced from: /usr/local/Cellar/ffmpeg/4.3.1_4/lib/libavfilter.7.85.100.dylib
  Reason: tried: '/usr/local/opt/srt/lib/libsrt.1.dylib' (no such file), '/usr/local/lib/libsrt.1.dylib' (no such file), '/usr/lib/libsrt.1.dylib' (no such file), '/usr/local/Cellar/srt/1.4.4/lib/libsrt.1.dylib' (no such file), '/usr/local/lib/libsrt.1.dylib' (no such file), '/usr/lib/libsrt.1.dylib' (no such file)
zsh: abort      ffmpegthumbnailer -s 0 -i  -o  -t 00:00:10
```

**Comment by dirkvdb** [comment] 2024-09-13 19:10
Closing, cannot reproduce. Feel free to reopen

**Closed by dirkvdb** 2024-09-13 19:10 UTC
