### ISSUE TITLE
Atamp to thumbnail a damaged video file will cause crash!

### ISSUE THREAD

**Issue by tommego** [dirkvdb/ffmpegthumbnailer#144] opened 2016-09-14 02:13 UTC
Hello ! I'm using this lib for thumbnailing video files.when I thumbnailed a damaged file it would crash and I found it coccured on PngWriter class. When a failed frame is atempt to be writen,with zero width and height ,and called function writeFrame(),my solution is to check if the encoming width and height are zero,and skip next work if they are zero.
my code as following :
```c++
void PngWriter::writeFrame(uint8_t** rgbData, int width, int height, int /*quality*/)
{
  //for some cases like thumbnailing a damaged video files,it should skip the following step and avoid crash
  if(width<=0 || height<= 0)
    return ;
    if (setjmp(png_jmpbuf(m_PngPtr)))
	{
		throw logic_error("Writing png file failed");
    return ;
	}

	png_set_IHDR(m_PngPtr, m_InfoPtr, width, height, 8,
				 PNG_COLOR_TYPE_RGB, PNG_INTERLACE_NONE,
				 PNG_COMPRESSION_TYPE_DEFAULT, PNG_FILTER_TYPE_DEFAULT);

    png_set_rows(m_PngPtr, m_InfoPtr, rgbData);
    png_write_png(m_PngPtr, m_InfoPtr, 0, NULL);
}
```

**Comment by dirkvdb** [comment] 2016-09-17 06:29
Can you provide me the damaged file. Then I can make a fix that will also work in case of jpeg output

**Comment by tommego** [comment] 2016-09-18 01:12
On my forked reposity has a file named damaged.swf, you download it to check out what happen. link as follow:
https://github.com/tommego/ffmpegthumbnailer

**Comment by tommego** [comment] 2016-09-18 01:15
![image](https://cloud.githubusercontent.com/assets/9795054/18612037/4a56f72c-7d80-11e6-8351-35be6943b0be.png)
I added a if statement in your source code and rebuild it , and then it didn't crash , just do nothing for a dramaged file.

**Comment by tommego** [comment] 2016-09-19 08:20
Sorry , I found whtat happen on it,because I used that lib whitout catching the given exceptions.Thank you anyway.

**Comment by dirkvdb** [comment] 2016-09-19 18:55
I cannot reproduce the issue with your, the latest ffmpeg creates a thumbnail out of it.

However, I committed a change that will give a proper error if the size is 0.

**Closed by dirkvdb** 2016-09-19 18:55 UTC

**Comment by tommego** [comment] 2016-09-20 01:57
@dirkvdb Ok, thanks you for your reply!
